name: drtshock

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/drtshock.yml'
  schedule:
    - cron: '0 0 */3 * *'

jobs: 
  PlayerVaults:
    uses: Dungjava/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "drtshock/PlayerVaults"
      name: "PlayerVaults"
      java: 17
 
