name: Dungjava

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/Dungjava.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  Panilla:
    uses: Dungjava/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "Dungjava/ValhallaMMO"
      name: "ValhallaMMO"
      target: "dist/target/*.jar"
      java: |
        17
        21
      commands: |
        curl -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        JAVA_HOME_17="JAVA_HOME_17_${RUNNER_ARCH}"
        JAVA_HOME_21="JAVA_HOME_21_${RUNNER_ARCH}"
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.19 --compile spigot --remapped
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.19.3 --compile spigot --remapped
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.19.4 --compile spigot --remapped
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.20.1 --compile spigot --remapped
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.20.2 --compile spigot --remapped
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.20.4 --compile spigot --remapped
        "${!JAVA_HOME_21}"/bin/java -jar BuildTools.jar --rev 1.20.6 --compile spigot --remapped
        "${!JAVA_HOME_21}"/bin/java -jar BuildTools.jar --rev 1.21.1 --compile spigot --remapped
        "${!JAVA_HOME_21}"/bin/java -jar BuildTools.jar --rev 1.21.3 --compile spigot --remapped
